# Stage 0: Base image
# - Use Node.js 24 on Alpine Linux as the common base for all stages (small image, fast builds).
FROM node:24.12.0-alpine AS base


# Stage 1: Dependencies layer
# - Install node_modules in a separate stage so Docker can cache it when source code changes.
FROM base AS deps
# - All app files will live under /app inside the container.
WORKDIR /app

# - Copy only dependency manifests first (best practice for caching).
# - yarn.lock* allows build to work even if the lockfile name is slightly different (e.g., in some templates).
COPY package.json yarn.lock* ./

# - Install dependencies using Yarn only.
# - --frozen-lockfile ensures yarn.lock is not modified and fails if it doesn't match package.json.
# - If the lockfile is missing, fail the build on purpose (reproducible builds).
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi


# Stage 2: Build layer
# - Copy source code and run `yarn build` (Next.js build output is created here).
FROM base AS builder
WORKDIR /app

# - Reuse the installed dependencies from the deps stage (no reinstall needed).
COPY --from=deps /app/node_modules ./node_modules

# - Copy the rest of the project files (source, config, etc.) into the build stage.
COPY . .

# - Disable Next.js telemetry during build (avoids sending anonymous usage data).
ENV NEXT_TELEMETRY_DISABLED=1

# - Run the production build.
# - Again, enforce that yarn.lock exists to keep the build deterministic.
RUN \
  if [ -f yarn.lock ]; then yarn run build; \
  else echo "Lockfile not found." && exit 1; \
  fi


# Stage 3: Runtime layer
# - Final image that contains only the built output needed to run the app.
FROM base AS runner
WORKDIR /app

# - Copy static public assets (served as-is).
COPY --from=builder /app/public ./public

# - Copy Next.js standalone server output (server.js + minimal node_modules bundle generated by Next).
# - --chown=nextjs:nodejs sets ownership, but note: this Dockerfile doesn't create these users/groups.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# - Copy Next.js static build assets (JS/CSS chunks, etc.).
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# - Expose the port your app will listen on inside the container.
EXPOSE 29790

# - Set runtime port environment variable (commonly used by Next/server.js).
ENV PORT=29790

# - Start the Next.js standalone server (generated during `yarn build`).
CMD ["node", "server.js"]
