import {
  faBars,
  faLongArrowAltRight,
  faArrowRight,
  faBell,
  faCog,
  faUser,
  faUserCircle,
  faAddressCard,
  faChartBar,
  faHome,
  faBriefcase,
  faFileAlt,
  faCoins,
  faBullhorn,
  faScroll,
  faUsersCog,
  faEdit,
  faWindowClose,
  faCheckSquare,
  faFileExcel,
  faFileCsv,
  faFilePdf,
  faFileExport,
  faCaretDown,
  faCaretUp,
  faCaretLeft,
  faCaretRight,
  faSearch,
  faChartArea,
  faEye,
  faCopy,
  faCommentDots,
  faPlus,
  faUpload,
  faExclamationCircle,
  faExchangeAlt,
  faFlag,
  faInfoCircle,
  faSlidersH,
  faArrowLeft,
  faCheck,
  faAngleRight,
  faSignOutAlt,
  faCalculator,
  faTh,
  faFilter,
  faTrash,
  faFileArrowDown,
  faBan,
  faRepeat,
  faStar,
  faBook,
  faGear,
  faFileMedical,
  faDatabase,
  faDownload,
  faAnglesDown,
  faCircle,
  faSun,
  faMoon,
  faEllipsisVertical,
  faSort,
  faSortUp,
  faSortDown,
  faFilterCircleXmark,
  faLanguage,
  faTurkishLiraSign,
  faUsers,
  faUserGear,
  faPhone,
  faEyeSlash,
  faXmark
} from '@fortawesome/free-solid-svg-icons';

export const ICON_LIST = {
  BARS: faBars,
  LONG_ARROW_RIGHT: faLongArrowAltRight,
  ARROW_RIGHT: faArrowRight,
  ARROW_LEFT: faArrowLeft,
  BELL: faBell,
  COG: faCog,
  USER: faUser,
  USER_CIRCLE: faUserCircle,
  ADDRESS_CARD: faAddressCard,
  CHART_BAR: faChartBar,
  CHART_AREA: faChartArea,
  HOME: faHome,
  BRIEFCASE: faBriefcase,
  FILE_ALT: faFileAlt,
  COINS: faCoins,
  BULLHORN: faBullhorn,
  SCROLL: faScroll,
  USERS_COG: faUsersCog,
  EDIT: faEdit,
  CLOSE: faWindowClose,
  CHECK: faCheckSquare,
  CHECK_DEFAULT: faCheck,
  EXCEL: faFileExcel,
  PDF: faFilePdf,
  CSV: faFileCsv,
  EXPORT: faFileExport,
  DOWNLOAD: faDownload,
  CARET_DOWN: faCaretDown,
  SORT_UPCARET_UP: faCaretUp,
  CARET_LEFT: faCaretLeft,
  CARET_RIGHT: faCaretRight,
  SEARCH: faSearch,
  EYE: faEye,
  COPY: faCopy,
  COMMENTS: faCommentDots,
  PLUS: faPlus,
  UPLOAD: faUpload,
  EXCLAMATION: faExclamationCircle,
  SWAP: faExchangeAlt,
  FLAG: faFlag,
  INFO: faInfoCircle,
  SLIDERS: faSlidersH,
  ANGEL_RIGHT: faAngleRight,
  LOGOUT: faSignOutAlt,
  CALCULATOR: faCalculator,
  TH: faTh,
  FILTER: faFilter,
  FILTER_CLEAR: faFilterCircleXmark,
  DELETE: faTrash,
  FILE_ARROW_DOWN: faFileArrowDown,
  BAN: faBan,
  REPEAT: faRepeat,
  STAR: faStar,
  BOOK: faBook,
  SETTINGS: faGear,
  PLUS_FILE: faFileMedical,
  DATABASE: faDatabase,
  SELECTABLE_ARROW: faAnglesDown,
  CIRCLE: faCircle,
  SUN: faSun,
  MOON: faMoon,
  VERTICAL_DOTS: faEllipsisVertical,
  SORT: faSort,
  SORT_DOWN: faSortDown,
  SORT_UP: faSortUp,
  LANGUAGE: faLanguage,
  TURKISH_LIRA: faTurkishLiraSign,
  USERS: faUsers,
  USER_GEAR: faUserGear,
  PHONE: faPhone,
  EYE_SLASH: faEyeSlash,
  REMOVE: faXmark
};
