import {
	faHome,
	faEdit,
	faWindowClose,
	faSearch,
	faPlus,
	faArrowLeft,
	faSignOutAlt,
	faTrash,
	faGear,
	faFilterCircleXmark,
	faUsers,
	faMapPin,
	faMobile,
	faMapLocation,
	faCopy,
	faCheck,
} from "@fortawesome/free-solid-svg-icons";

export const ICON_LIST = {
	ARROW_LEFT: faArrowLeft,
	CLOSE: faWindowClose,
	HOME: faHome,
	EDIT: faEdit,
	SEARCH: faSearch,
	PLUS: faPlus,
	LOGOUT: faSignOutAlt,
	FILTER_CLEAR: faFilterCircleXmark,
	DELETE: faTrash,
	SETTINGS: faGear,
	USERS: faUsers,
	MAP_PIN: faMapPin,
	MOBILE: faMobile,
	MAP_LOCATION: faMapLocation,
	COPY: faCopy,
	CHECK: faCheck,
};
