# Purpose: This file is used for check application health.

# Name of the workflow
name: Application Status

on:
  push:
    branches:
      - main # Trigger the workflow when a push event occurs on the main branch

jobs:
  build: # Define the "build" job
    runs-on: ubuntu-latest # Run the job on the latest version of Ubuntu
    steps: # List of steps to execute within the job
      - name: Checkout code # Step to check out the code from the repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/initialize-environment
        with:
          GH_USERNAME: ${{ vars.GH_USERNAME }}
          GH_USER_ACCESS_TOKEN: ${{ secrets.GH_USER_ACCESS_TOKEN }}

      - name: Install and Build # Step to install and build the project with npm
        run: |
          npm install
          npm run build

  sonarqube:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code # Step to check out the code from the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Initialize environment
        uses: ./.github/actions/initialize-environment
        with:
          GH_USERNAME: ${{ vars.GH_USERNAME }}
          GH_USER_ACCESS_TOKEN: ${{ secrets.GH_USER_ACCESS_TOKEN }}

      - name: SonarQube Scan # Step to run SonarQube scan
        uses: sonarsource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.projectName=ays-fe-institution
